### ISSUE TITLE
Creation of intervals in running activities fails

### ISSUE THREAD

**Issue by Zepp333333** [Zepp333333/Cyclist-Performance#1]
When trying to create interval in running activity application fails with below trace. However heartrate data series exist in df. 
According to my quick research, following code in RussingInterval:populate_metrics for some reasons returns empty df:
`df = dataframe.iloc[self.start:self.end]`

Apparently Interval class has a bug as sometimes instances have start and end fields as None

```
Traceback (most recent call last):
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/dash/dash.py", line 1096, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/venv/lib/python3.9/site-packages/dash/dash.py", line 1017, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/hardio/dashapp/interval_callbacks.py", line 50, in manage_intervals
    activity.new_interval(*interval_range)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/logic/activity.py", line 61, in new_interval
    self.add_intervals([self._make_interval(start, end, name)])
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/logic/activity.py", line 71, in _make_interval
    return interval.create(id=len(self.intervals),
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/logic/interval.py", line 36, in create
    self.populate_metrics(dataframe)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/logic/interval.py", line 118, in populate_metrics
    self.populate_hr(df)
  File "/Users/Sergey/Documents/OneDrive/Coding/Projects/HARDIO/logic/interval.py", line 126, in populate_hr
    self.avg_hr = int(df.heartrate.mean())
ValueError: cannot convert float NaN to integer
```

**Comment by Zepp333333** [comment]
This is likely not an issue with Interval. This might be an isssue with running data-streams that are being written every 5 sec by garmin so time and index are not the same. It fails here in Running Interval:
`df = dataframe.iloc[self.start:self.end]` 
as start and end values are based on second, while iloc slices by index which is 5 times smaller that time series...
